### ISSUE TITLE
4월15일 이벤트에서 질문/토의했으면 하는 주제가 있으면 제안해주세요 

### ISSUE THREAD

**Issue by hollobit** [hollobit/AIML-in-Medicine-club#4]
4월15일에는 다음과 같은 주제들을 논의할 예정입니다. 

* 의료 인공지능 성능 평가 가이드라인 개발에 관한 사항 - 어떤 가이드라인이 필요한가 ? 
* Special Talk : Data Augmentation (프로메디우스 배현진 대표, 연세대 김휘영 교수, 서울여대 홍헬렌 교수) 
     * 데이터 증강 및 합성 데이터 기술 및 응용
     * 합성 데이터 관련 이슈들 
     * Visual Turing Test  

위의 주제와 관련해 질문하시거나 논의했으면 하는 주제가 있으면 이슈에 올려주세요.

**Comment by namupark** [comment]
안녕하세요, 매주 참신한 주제에 대한 깊이 있는 토론 잘 듣고있습니다. 개인적으로 궁금했던 부분이 있어 질문드립니다.

이전에 흉수 데이터를 통해 연구를 진행한 적이 있는데, 해당 데이터가 양적으로 부족해서 Data Augmentation 기법을 사용한 적이 있습니다. 다만, 원본 데이터 자체에 Noise (잘못 기입된 값, 누락값) 가 매우 많아 어려움이 있었습니다. raw data가 noisy한 상황이라, 증강된 데이터 역시 잡음이 많이 포함되어 있었을 것으로 보이는데, 이는 데이터의 수가 유의미하게 많아지면 해결되는 문제일까요? 아니면, 각종 정규화 기법 또는 수작업으로 데이터를 정제하는 작업이 반드시  수반되어야 할까요? (이전에 다뤄주셨던 데이터 Quality에 대한 이야기와도 이어지는 것 같습니다)

감사합니다.
