### ISSUE TITLE
클럽 가입

### ISSUE THREAD

**Issue by wonsang** [hollobit/AIML-in-Medicine-club#5]
클럽에 가입하려면 반드시 iPhone에서만 가능한지요?

**Comment by hollobit** [comment]
이 행사는 클럽 회원이 아니라도 참여하실 수 있도록 되어 있습니다. 

클럽하우스 청취도 안드로이드용 비공식 앱으로 들으실 수 있습니다. 

비공식 앱에서 제약이 많다는 것은 알고 있는데, 클럽 가입 신청이 가능하신지는 제가 잘 모르겠네요.

**Comment by hollobit** [comment]
지난 주에 안드로이드 공식 앱도 출시되었습니다. 

다음 링크로 접속하시면 초대 없이 클럽하우스와 의료인공지능 클럽 가입도 가능하십니다. 

https://www.clubhouse.com/join/aiml-in-medicine/fvzQHLyQ
