### ISSUE TITLE
4월29일 논의 주제에 대한 의견들

### ISSUE THREAD

**Issue by hollobit** [hollobit/AIML-in-Medicine-club#7]
4월29일에는 다음과 같은 주제들을 논의할 예정입니다.

- 주요 뉴스들에 대한 코멘트 
- Special Talk : 의료 인공지능의 단점, 위험, 그리고 한계 (부제: 과연 의료 인공지능 비즈니스가 성공할 수 있을까? 시장과 비즈니스를 키우기 위해 필요한 것은?)
- 의료 인공지능에 대해 무엇이든 물어보세요

위의 주제와 관련해 질문하시거나 논의했으면 하는 주제가 있으면 이슈에 올려주세요.

**Comment by ziwonSeo-lab** [comment]
1. 단점, 위험, 한계 
>> 정확도가 100%될수 없을것으로 생각되기에, 판단자가 있어야 할것이고 책임여부, 환자의 선택 문제 등이 있을것같다.
>> 판단 이유에 대한 근거를 알기 어렵다.

2. 비지니스를 키우기 위해 필요한 것
>>  데이터 !!  환자의 개인정보 보호가 중요하기 때문에, 질병에 대한 데이터가 거의 공유되지않고 각 병원에서 연구하고 있는 상황.
>> 개인이 식별되지 않고, 질병과 개인정보를 공유할 수 있는 처리 기법과 정책 필요

**Comment by astaria82** [comment]
대한의료인공지능학회의 춘계학술대회 사전등록 링크입니다.
https://www.kosaim.org/html/?pmode=inputList
